apiVersion: v1
kind: Service
metadata:
  name: argocdlocalproject
  namespace: default
  labels:
    app: argocdlocalproject
spec:
  selector:
    app: argocdlocalproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
